import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";
import type { Metadata } from "next";

import Header from "@/components/Header/header";

export const metadata: Metadata = {
  title: "Доставка еды и продуктов от 30 минут в Минске",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header></Header>
        <main>{children}</main>
        <div></div>
        {/* footer place */}
      </body>
    </html>
  );
}
